In [15]:
import pandas as pd
from datetime import datetime, timedelta
import random

# Number of records
num_records = 1000000

# Data dictionary for CSV creation
data = {
    'start_time': [],
    'end_time': [],
    'measurement': [],
    'samples': []
}

# Start time
start_time = datetime.now()

for i in range(num_records):
    # Random time delta between 0 and 100 seconds
    time_delta = timedelta(seconds=random.randint(0, 100))

    # Calculate end time
    end_time = start_time + time_delta

    # Random measurement (float) between -10 and 50
    value = random.uniform(-10, 50)
    
    # Random samples (float) between 5 and 15
    samples = random.randint(5, 15)

    # Insert data into the DataFrame
    data['start_time'].append(start_time)
    data['end_time'].append(end_time)
    data['measurement'].append(value)
    data['samples'].append(samples)

    # Set new start time for the next record
    start_time = end_time

# Create DataFrame
df = pd.DataFrame(data)

# Export DataFrame to a CSV file
df.to_csv('measurement_data.csv', index=False)

In [16]:
df = pd.read_csv('/Users/maximkiesel/batch_processing_IaC_AWS/measurement_data.csv')

In [17]:
df.head()

,start_time,end_time,measurement,samples
0,2023-06-26 21:05:00.474245,2023-06-26 21:05:39.474245,10.855277,10
1,2023-06-26 21:05:39.474245,2023-06-26 21:06:27.474245,23.786845,6
2,2023-06-26 21:06:27.474245,2023-06-26 21:07:13.474245,24.864929,7
3,2023-06-26 21:07:13.474245,2023-06-26 21:07:51.474245,38.131946,10
4,2023-06-26 21:07:51.474245,2023-06-26 21:08:32.474245,21.166757,12